'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("DTCotizCompra"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DTCotizCompra
    Inherits Global.System.Data.DataSet
    
    Private tableOrdenCompra As OrdenCompraDataTable
    
    Private tableOrdenCompraDetalle As OrdenCompraDetalleDataTable
    
    Private relationOrdenCompra_OrdenCompraDetalle As Global.System.Data.DataRelation
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("OrdenCompra")) Is Nothing) Then
                MyBase.Tables.Add(New OrdenCompraDataTable(ds.Tables("OrdenCompra")))
            End If
            If (Not (ds.Tables("OrdenCompraDetalle")) Is Nothing) Then
                MyBase.Tables.Add(New OrdenCompraDetalleDataTable(ds.Tables("OrdenCompraDetalle")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property OrdenCompra() As OrdenCompraDataTable
        Get
            Return Me.tableOrdenCompra
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property OrdenCompraDetalle() As OrdenCompraDetalleDataTable
        Get
            Return Me.tableOrdenCompraDetalle
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As DTCotizCompra = CType(MyBase.Clone,DTCotizCompra)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("OrdenCompra")) Is Nothing) Then
                MyBase.Tables.Add(New OrdenCompraDataTable(ds.Tables("OrdenCompra")))
            End If
            If (Not (ds.Tables("OrdenCompraDetalle")) Is Nothing) Then
                MyBase.Tables.Add(New OrdenCompraDetalleDataTable(ds.Tables("OrdenCompraDetalle")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableOrdenCompra = CType(MyBase.Tables("OrdenCompra"),OrdenCompraDataTable)
        If (initTable = true) Then
            If (Not (Me.tableOrdenCompra) Is Nothing) Then
                Me.tableOrdenCompra.InitVars
            End If
        End If
        Me.tableOrdenCompraDetalle = CType(MyBase.Tables("OrdenCompraDetalle"),OrdenCompraDetalleDataTable)
        If (initTable = true) Then
            If (Not (Me.tableOrdenCompraDetalle) Is Nothing) Then
                Me.tableOrdenCompraDetalle.InitVars
            End If
        End If
        Me.relationOrdenCompra_OrdenCompraDetalle = Me.Relations("OrdenCompra_OrdenCompraDetalle")
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "DTCotizCompra"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DTOrdenCompra.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableOrdenCompra = New OrdenCompraDataTable
        MyBase.Tables.Add(Me.tableOrdenCompra)
        Me.tableOrdenCompraDetalle = New OrdenCompraDetalleDataTable
        MyBase.Tables.Add(Me.tableOrdenCompraDetalle)
        Me.relationOrdenCompra_OrdenCompraDetalle = New Global.System.Data.DataRelation("OrdenCompra_OrdenCompraDetalle", New Global.System.Data.DataColumn() {Me.tableOrdenCompra.CodigoColumn}, New Global.System.Data.DataColumn() {Me.tableOrdenCompraDetalle.CodigoColumn}, false)
        Me.Relations.Add(Me.relationOrdenCompra_OrdenCompraDetalle)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeOrdenCompra() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeOrdenCompraDetalle() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DTCotizCompra = New DTCotizCompra
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub OrdenCompraRowChangeEventHandler(ByVal sender As Object, ByVal e As OrdenCompraRowChangeEvent)
    
    Public Delegate Sub OrdenCompraDetalleRowChangeEventHandler(ByVal sender As Object, ByVal e As OrdenCompraDetalleRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class OrdenCompraDataTable
        Inherits Global.System.Data.TypedTableBase(Of OrdenCompraRow)
        
        Private columnCodigo As Global.System.Data.DataColumn
        
        Private columnTitulo As Global.System.Data.DataColumn
        
        Private columnORDCO_FechaDocumento As Global.System.Data.DataColumn
        
        Private columnORDCO_AtencionProveedor As Global.System.Data.DataColumn
        
        Private columnORDCO_TelefonoProveedor As Global.System.Data.DataColumn
        
        Private columnORDCO_CorreoProveedor As Global.System.Data.DataColumn
        
        Private columnORDCO_Condiciones As Global.System.Data.DataColumn
        
        Private columnORDCO_ImporteCompra As Global.System.Data.DataColumn
        
        Private columnORDCO_TotalCompra As Global.System.Data.DataColumn
        
        Private columnORDCO_ImporteIgv As Global.System.Data.DataColumn
        
        Private columnORDCO_DireccionProveedor As Global.System.Data.DataColumn
        
        Private columnENTID_Proveedor As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "OrdenCompra"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CodigoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCodigo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property TituloColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTitulo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ORDCO_FechaDocumentoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnORDCO_FechaDocumento
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ORDCO_AtencionProveedorColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnORDCO_AtencionProveedor
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ORDCO_TelefonoProveedorColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnORDCO_TelefonoProveedor
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ORDCO_CorreoProveedorColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnORDCO_CorreoProveedor
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ORDCO_CondicionesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnORDCO_Condiciones
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ORDCO_ImporteCompraColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnORDCO_ImporteCompra
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ORDCO_TotalCompraColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnORDCO_TotalCompra
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ORDCO_ImporteIgvColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnORDCO_ImporteIgv
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ORDCO_DireccionProveedorColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnORDCO_DireccionProveedor
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ENTID_ProveedorColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnENTID_Proveedor
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As OrdenCompraRow
            Get
                Return CType(Me.Rows(index),OrdenCompraRow)
            End Get
        End Property
        
        Public Event OrdenCompraRowChanging As OrdenCompraRowChangeEventHandler
        
        Public Event OrdenCompraRowChanged As OrdenCompraRowChangeEventHandler
        
        Public Event OrdenCompraRowDeleting As OrdenCompraRowChangeEventHandler
        
        Public Event OrdenCompraRowDeleted As OrdenCompraRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddOrdenCompraRow(ByVal row As OrdenCompraRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddOrdenCompraRow(ByVal Codigo As String, ByVal Titulo As String, ByVal ORDCO_FechaDocumento As Date, ByVal ORDCO_AtencionProveedor As String, ByVal ORDCO_TelefonoProveedor As String, ByVal ORDCO_CorreoProveedor As String, ByVal ORDCO_Condiciones As String, ByVal ORDCO_ImporteCompra As Decimal, ByVal ORDCO_TotalCompra As Decimal, ByVal ORDCO_ImporteIgv As Decimal, ByVal ORDCO_DireccionProveedor As String, ByVal ENTID_Proveedor As String) As OrdenCompraRow
            Dim rowOrdenCompraRow As OrdenCompraRow = CType(Me.NewRow,OrdenCompraRow)
            Dim columnValuesArray() As Object = New Object() {Codigo, Titulo, ORDCO_FechaDocumento, ORDCO_AtencionProveedor, ORDCO_TelefonoProveedor, ORDCO_CorreoProveedor, ORDCO_Condiciones, ORDCO_ImporteCompra, ORDCO_TotalCompra, ORDCO_ImporteIgv, ORDCO_DireccionProveedor, ENTID_Proveedor}
            rowOrdenCompraRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowOrdenCompraRow)
            Return rowOrdenCompraRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function FindByCodigo(ByVal Codigo As String) As OrdenCompraRow
            Return CType(Me.Rows.Find(New Object() {Codigo}),OrdenCompraRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As OrdenCompraDataTable = CType(MyBase.Clone,OrdenCompraDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New OrdenCompraDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnCodigo = MyBase.Columns("Codigo")
            Me.columnTitulo = MyBase.Columns("Titulo")
            Me.columnORDCO_FechaDocumento = MyBase.Columns("ORDCO_FechaDocumento")
            Me.columnORDCO_AtencionProveedor = MyBase.Columns("ORDCO_AtencionProveedor")
            Me.columnORDCO_TelefonoProveedor = MyBase.Columns("ORDCO_TelefonoProveedor")
            Me.columnORDCO_CorreoProveedor = MyBase.Columns("ORDCO_CorreoProveedor")
            Me.columnORDCO_Condiciones = MyBase.Columns("ORDCO_Condiciones")
            Me.columnORDCO_ImporteCompra = MyBase.Columns("ORDCO_ImporteCompra")
            Me.columnORDCO_TotalCompra = MyBase.Columns("ORDCO_TotalCompra")
            Me.columnORDCO_ImporteIgv = MyBase.Columns("ORDCO_ImporteIgv")
            Me.columnORDCO_DireccionProveedor = MyBase.Columns("ORDCO_DireccionProveedor")
            Me.columnENTID_Proveedor = MyBase.Columns("ENTID_Proveedor")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnCodigo = New Global.System.Data.DataColumn("Codigo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCodigo)
            Me.columnTitulo = New Global.System.Data.DataColumn("Titulo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTitulo)
            Me.columnORDCO_FechaDocumento = New Global.System.Data.DataColumn("ORDCO_FechaDocumento", GetType(Date), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnORDCO_FechaDocumento)
            Me.columnORDCO_AtencionProveedor = New Global.System.Data.DataColumn("ORDCO_AtencionProveedor", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnORDCO_AtencionProveedor)
            Me.columnORDCO_TelefonoProveedor = New Global.System.Data.DataColumn("ORDCO_TelefonoProveedor", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnORDCO_TelefonoProveedor)
            Me.columnORDCO_CorreoProveedor = New Global.System.Data.DataColumn("ORDCO_CorreoProveedor", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnORDCO_CorreoProveedor)
            Me.columnORDCO_Condiciones = New Global.System.Data.DataColumn("ORDCO_Condiciones", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnORDCO_Condiciones)
            Me.columnORDCO_ImporteCompra = New Global.System.Data.DataColumn("ORDCO_ImporteCompra", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnORDCO_ImporteCompra)
            Me.columnORDCO_TotalCompra = New Global.System.Data.DataColumn("ORDCO_TotalCompra", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnORDCO_TotalCompra)
            Me.columnORDCO_ImporteIgv = New Global.System.Data.DataColumn("ORDCO_ImporteIgv", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnORDCO_ImporteIgv)
            Me.columnORDCO_DireccionProveedor = New Global.System.Data.DataColumn("ORDCO_DireccionProveedor", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnORDCO_DireccionProveedor)
            Me.columnENTID_Proveedor = New Global.System.Data.DataColumn("ENTID_Proveedor", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnENTID_Proveedor)
            Me.Constraints.Add(New Global.System.Data.UniqueConstraint("Constraint1", New Global.System.Data.DataColumn() {Me.columnCodigo}, true))
            Me.columnCodigo.AllowDBNull = false
            Me.columnCodigo.Unique = true
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewOrdenCompraRow() As OrdenCompraRow
            Return CType(Me.NewRow,OrdenCompraRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New OrdenCompraRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(OrdenCompraRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.OrdenCompraRowChangedEvent) Is Nothing) Then
                RaiseEvent OrdenCompraRowChanged(Me, New OrdenCompraRowChangeEvent(CType(e.Row,OrdenCompraRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.OrdenCompraRowChangingEvent) Is Nothing) Then
                RaiseEvent OrdenCompraRowChanging(Me, New OrdenCompraRowChangeEvent(CType(e.Row,OrdenCompraRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.OrdenCompraRowDeletedEvent) Is Nothing) Then
                RaiseEvent OrdenCompraRowDeleted(Me, New OrdenCompraRowChangeEvent(CType(e.Row,OrdenCompraRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.OrdenCompraRowDeletingEvent) Is Nothing) Then
                RaiseEvent OrdenCompraRowDeleting(Me, New OrdenCompraRowChangeEvent(CType(e.Row,OrdenCompraRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveOrdenCompraRow(ByVal row As OrdenCompraRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As DTCotizCompra = New DTCotizCompra
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "OrdenCompraDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class OrdenCompraDetalleDataTable
        Inherits Global.System.Data.TypedTableBase(Of OrdenCompraDetalleRow)
        
        Private columnORDCD_Item As Global.System.Data.DataColumn
        
        Private columnARTIC_Descripcion As Global.System.Data.DataColumn
        
        Private columnORDCD_Cantidad As Global.System.Data.DataColumn
        
        Private columnORDCD_PrecioUnitario As Global.System.Data.DataColumn
        
        Private columnORDCD_SubImporteCompra As Global.System.Data.DataColumn
        
        Private columnCodigo As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "OrdenCompraDetalle"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ORDCD_ItemColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnORDCD_Item
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ARTIC_DescripcionColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnARTIC_Descripcion
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ORDCD_CantidadColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnORDCD_Cantidad
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ORDCD_PrecioUnitarioColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnORDCD_PrecioUnitario
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ORDCD_SubImporteCompraColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnORDCD_SubImporteCompra
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CodigoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCodigo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As OrdenCompraDetalleRow
            Get
                Return CType(Me.Rows(index),OrdenCompraDetalleRow)
            End Get
        End Property
        
        Public Event OrdenCompraDetalleRowChanging As OrdenCompraDetalleRowChangeEventHandler
        
        Public Event OrdenCompraDetalleRowChanged As OrdenCompraDetalleRowChangeEventHandler
        
        Public Event OrdenCompraDetalleRowDeleting As OrdenCompraDetalleRowChangeEventHandler
        
        Public Event OrdenCompraDetalleRowDeleted As OrdenCompraDetalleRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddOrdenCompraDetalleRow(ByVal row As OrdenCompraDetalleRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddOrdenCompraDetalleRow(ByVal ORDCD_Item As Integer, ByVal ARTIC_Descripcion As String, ByVal ORDCD_Cantidad As Decimal, ByVal ORDCD_PrecioUnitario As Decimal, ByVal ORDCD_SubImporteCompra As Decimal, ByVal parentOrdenCompraRowByOrdenCompra_OrdenCompraDetalle As OrdenCompraRow) As OrdenCompraDetalleRow
            Dim rowOrdenCompraDetalleRow As OrdenCompraDetalleRow = CType(Me.NewRow,OrdenCompraDetalleRow)
            Dim columnValuesArray() As Object = New Object() {ORDCD_Item, ARTIC_Descripcion, ORDCD_Cantidad, ORDCD_PrecioUnitario, ORDCD_SubImporteCompra, Nothing}
            If (Not (parentOrdenCompraRowByOrdenCompra_OrdenCompraDetalle) Is Nothing) Then
                columnValuesArray(5) = parentOrdenCompraRowByOrdenCompra_OrdenCompraDetalle(0)
            End If
            rowOrdenCompraDetalleRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowOrdenCompraDetalleRow)
            Return rowOrdenCompraDetalleRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function FindByORDCD_ItemCodigo(ByVal ORDCD_Item As Integer, ByVal Codigo As String) As OrdenCompraDetalleRow
            Return CType(Me.Rows.Find(New Object() {ORDCD_Item, Codigo}),OrdenCompraDetalleRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As OrdenCompraDetalleDataTable = CType(MyBase.Clone,OrdenCompraDetalleDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New OrdenCompraDetalleDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnORDCD_Item = MyBase.Columns("ORDCD_Item")
            Me.columnARTIC_Descripcion = MyBase.Columns("ARTIC_Descripcion")
            Me.columnORDCD_Cantidad = MyBase.Columns("ORDCD_Cantidad")
            Me.columnORDCD_PrecioUnitario = MyBase.Columns("ORDCD_PrecioUnitario")
            Me.columnORDCD_SubImporteCompra = MyBase.Columns("ORDCD_SubImporteCompra")
            Me.columnCodigo = MyBase.Columns("Codigo")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnORDCD_Item = New Global.System.Data.DataColumn("ORDCD_Item", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnORDCD_Item)
            Me.columnARTIC_Descripcion = New Global.System.Data.DataColumn("ARTIC_Descripcion", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnARTIC_Descripcion)
            Me.columnORDCD_Cantidad = New Global.System.Data.DataColumn("ORDCD_Cantidad", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnORDCD_Cantidad)
            Me.columnORDCD_PrecioUnitario = New Global.System.Data.DataColumn("ORDCD_PrecioUnitario", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnORDCD_PrecioUnitario)
            Me.columnORDCD_SubImporteCompra = New Global.System.Data.DataColumn("ORDCD_SubImporteCompra", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnORDCD_SubImporteCompra)
            Me.columnCodigo = New Global.System.Data.DataColumn("Codigo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCodigo)
            Me.Constraints.Add(New Global.System.Data.UniqueConstraint("Constraint1", New Global.System.Data.DataColumn() {Me.columnORDCD_Item, Me.columnCodigo}, true))
            Me.columnORDCD_Item.AllowDBNull = false
            Me.columnCodigo.AllowDBNull = false
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewOrdenCompraDetalleRow() As OrdenCompraDetalleRow
            Return CType(Me.NewRow,OrdenCompraDetalleRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New OrdenCompraDetalleRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(OrdenCompraDetalleRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.OrdenCompraDetalleRowChangedEvent) Is Nothing) Then
                RaiseEvent OrdenCompraDetalleRowChanged(Me, New OrdenCompraDetalleRowChangeEvent(CType(e.Row,OrdenCompraDetalleRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.OrdenCompraDetalleRowChangingEvent) Is Nothing) Then
                RaiseEvent OrdenCompraDetalleRowChanging(Me, New OrdenCompraDetalleRowChangeEvent(CType(e.Row,OrdenCompraDetalleRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.OrdenCompraDetalleRowDeletedEvent) Is Nothing) Then
                RaiseEvent OrdenCompraDetalleRowDeleted(Me, New OrdenCompraDetalleRowChangeEvent(CType(e.Row,OrdenCompraDetalleRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.OrdenCompraDetalleRowDeletingEvent) Is Nothing) Then
                RaiseEvent OrdenCompraDetalleRowDeleting(Me, New OrdenCompraDetalleRowChangeEvent(CType(e.Row,OrdenCompraDetalleRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveOrdenCompraDetalleRow(ByVal row As OrdenCompraDetalleRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As DTCotizCompra = New DTCotizCompra
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "OrdenCompraDetalleDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class OrdenCompraRow
        Inherits Global.System.Data.DataRow
        
        Private tableOrdenCompra As OrdenCompraDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableOrdenCompra = CType(Me.Table,OrdenCompraDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Codigo() As String
            Get
                Return CType(Me(Me.tableOrdenCompra.CodigoColumn),String)
            End Get
            Set
                Me(Me.tableOrdenCompra.CodigoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Titulo() As String
            Get
                Try 
                    Return CType(Me(Me.tableOrdenCompra.TituloColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Titulo' in table 'OrdenCompra' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableOrdenCompra.TituloColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ORDCO_FechaDocumento() As Date
            Get
                Try 
                    Return CType(Me(Me.tableOrdenCompra.ORDCO_FechaDocumentoColumn),Date)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ORDCO_FechaDocumento' in table 'OrdenCompra' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableOrdenCompra.ORDCO_FechaDocumentoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ORDCO_AtencionProveedor() As String
            Get
                Try 
                    Return CType(Me(Me.tableOrdenCompra.ORDCO_AtencionProveedorColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ORDCO_AtencionProveedor' in table 'OrdenCompra' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableOrdenCompra.ORDCO_AtencionProveedorColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ORDCO_TelefonoProveedor() As String
            Get
                Try 
                    Return CType(Me(Me.tableOrdenCompra.ORDCO_TelefonoProveedorColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ORDCO_TelefonoProveedor' in table 'OrdenCompra' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableOrdenCompra.ORDCO_TelefonoProveedorColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ORDCO_CorreoProveedor() As String
            Get
                Try 
                    Return CType(Me(Me.tableOrdenCompra.ORDCO_CorreoProveedorColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ORDCO_CorreoProveedor' in table 'OrdenCompra' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableOrdenCompra.ORDCO_CorreoProveedorColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ORDCO_Condiciones() As String
            Get
                Try 
                    Return CType(Me(Me.tableOrdenCompra.ORDCO_CondicionesColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ORDCO_Condiciones' in table 'OrdenCompra' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableOrdenCompra.ORDCO_CondicionesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ORDCO_ImporteCompra() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableOrdenCompra.ORDCO_ImporteCompraColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ORDCO_ImporteCompra' in table 'OrdenCompra' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableOrdenCompra.ORDCO_ImporteCompraColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ORDCO_TotalCompra() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableOrdenCompra.ORDCO_TotalCompraColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ORDCO_TotalCompra' in table 'OrdenCompra' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableOrdenCompra.ORDCO_TotalCompraColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ORDCO_ImporteIgv() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableOrdenCompra.ORDCO_ImporteIgvColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ORDCO_ImporteIgv' in table 'OrdenCompra' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableOrdenCompra.ORDCO_ImporteIgvColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ORDCO_DireccionProveedor() As String
            Get
                Try 
                    Return CType(Me(Me.tableOrdenCompra.ORDCO_DireccionProveedorColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ORDCO_DireccionProveedor' in table 'OrdenCompra' is DBNull."& _ 
                            "", e)
                End Try
            End Get
            Set
                Me(Me.tableOrdenCompra.ORDCO_DireccionProveedorColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ENTID_Proveedor() As String
            Get
                Try 
                    Return CType(Me(Me.tableOrdenCompra.ENTID_ProveedorColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ENTID_Proveedor' in table 'OrdenCompra' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableOrdenCompra.ENTID_ProveedorColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsTituloNull() As Boolean
            Return Me.IsNull(Me.tableOrdenCompra.TituloColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetTituloNull()
            Me(Me.tableOrdenCompra.TituloColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsORDCO_FechaDocumentoNull() As Boolean
            Return Me.IsNull(Me.tableOrdenCompra.ORDCO_FechaDocumentoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetORDCO_FechaDocumentoNull()
            Me(Me.tableOrdenCompra.ORDCO_FechaDocumentoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsORDCO_AtencionProveedorNull() As Boolean
            Return Me.IsNull(Me.tableOrdenCompra.ORDCO_AtencionProveedorColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetORDCO_AtencionProveedorNull()
            Me(Me.tableOrdenCompra.ORDCO_AtencionProveedorColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsORDCO_TelefonoProveedorNull() As Boolean
            Return Me.IsNull(Me.tableOrdenCompra.ORDCO_TelefonoProveedorColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetORDCO_TelefonoProveedorNull()
            Me(Me.tableOrdenCompra.ORDCO_TelefonoProveedorColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsORDCO_CorreoProveedorNull() As Boolean
            Return Me.IsNull(Me.tableOrdenCompra.ORDCO_CorreoProveedorColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetORDCO_CorreoProveedorNull()
            Me(Me.tableOrdenCompra.ORDCO_CorreoProveedorColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsORDCO_CondicionesNull() As Boolean
            Return Me.IsNull(Me.tableOrdenCompra.ORDCO_CondicionesColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetORDCO_CondicionesNull()
            Me(Me.tableOrdenCompra.ORDCO_CondicionesColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsORDCO_ImporteCompraNull() As Boolean
            Return Me.IsNull(Me.tableOrdenCompra.ORDCO_ImporteCompraColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetORDCO_ImporteCompraNull()
            Me(Me.tableOrdenCompra.ORDCO_ImporteCompraColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsORDCO_TotalCompraNull() As Boolean
            Return Me.IsNull(Me.tableOrdenCompra.ORDCO_TotalCompraColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetORDCO_TotalCompraNull()
            Me(Me.tableOrdenCompra.ORDCO_TotalCompraColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsORDCO_ImporteIgvNull() As Boolean
            Return Me.IsNull(Me.tableOrdenCompra.ORDCO_ImporteIgvColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetORDCO_ImporteIgvNull()
            Me(Me.tableOrdenCompra.ORDCO_ImporteIgvColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsORDCO_DireccionProveedorNull() As Boolean
            Return Me.IsNull(Me.tableOrdenCompra.ORDCO_DireccionProveedorColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetORDCO_DireccionProveedorNull()
            Me(Me.tableOrdenCompra.ORDCO_DireccionProveedorColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsENTID_ProveedorNull() As Boolean
            Return Me.IsNull(Me.tableOrdenCompra.ENTID_ProveedorColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetENTID_ProveedorNull()
            Me(Me.tableOrdenCompra.ENTID_ProveedorColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function GetOrdenCompraDetalleRows() As OrdenCompraDetalleRow()
            If (Me.Table.ChildRelations("OrdenCompra_OrdenCompraDetalle") Is Nothing) Then
                Return New OrdenCompraDetalleRow(-1) {}
            Else
                Return CType(MyBase.GetChildRows(Me.Table.ChildRelations("OrdenCompra_OrdenCompraDetalle")),OrdenCompraDetalleRow())
            End If
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class OrdenCompraDetalleRow
        Inherits Global.System.Data.DataRow
        
        Private tableOrdenCompraDetalle As OrdenCompraDetalleDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableOrdenCompraDetalle = CType(Me.Table,OrdenCompraDetalleDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ORDCD_Item() As Integer
            Get
                Return CType(Me(Me.tableOrdenCompraDetalle.ORDCD_ItemColumn),Integer)
            End Get
            Set
                Me(Me.tableOrdenCompraDetalle.ORDCD_ItemColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ARTIC_Descripcion() As String
            Get
                Try 
                    Return CType(Me(Me.tableOrdenCompraDetalle.ARTIC_DescripcionColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ARTIC_Descripcion' in table 'OrdenCompraDetalle' is DBNull."& _ 
                            "", e)
                End Try
            End Get
            Set
                Me(Me.tableOrdenCompraDetalle.ARTIC_DescripcionColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ORDCD_Cantidad() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableOrdenCompraDetalle.ORDCD_CantidadColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ORDCD_Cantidad' in table 'OrdenCompraDetalle' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableOrdenCompraDetalle.ORDCD_CantidadColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ORDCD_PrecioUnitario() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableOrdenCompraDetalle.ORDCD_PrecioUnitarioColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ORDCD_PrecioUnitario' in table 'OrdenCompraDetalle' is DBNu"& _ 
                            "ll.", e)
                End Try
            End Get
            Set
                Me(Me.tableOrdenCompraDetalle.ORDCD_PrecioUnitarioColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ORDCD_SubImporteCompra() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tableOrdenCompraDetalle.ORDCD_SubImporteCompraColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ORDCD_SubImporteCompra' in table 'OrdenCompraDetalle' is DB"& _ 
                            "Null.", e)
                End Try
            End Get
            Set
                Me(Me.tableOrdenCompraDetalle.ORDCD_SubImporteCompraColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Codigo() As String
            Get
                Return CType(Me(Me.tableOrdenCompraDetalle.CodigoColumn),String)
            End Get
            Set
                Me(Me.tableOrdenCompraDetalle.CodigoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property OrdenCompraRow() As OrdenCompraRow
            Get
                Return CType(Me.GetParentRow(Me.Table.ParentRelations("OrdenCompra_OrdenCompraDetalle")),OrdenCompraRow)
            End Get
            Set
                Me.SetParentRow(value, Me.Table.ParentRelations("OrdenCompra_OrdenCompraDetalle"))
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsARTIC_DescripcionNull() As Boolean
            Return Me.IsNull(Me.tableOrdenCompraDetalle.ARTIC_DescripcionColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetARTIC_DescripcionNull()
            Me(Me.tableOrdenCompraDetalle.ARTIC_DescripcionColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsORDCD_CantidadNull() As Boolean
            Return Me.IsNull(Me.tableOrdenCompraDetalle.ORDCD_CantidadColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetORDCD_CantidadNull()
            Me(Me.tableOrdenCompraDetalle.ORDCD_CantidadColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsORDCD_PrecioUnitarioNull() As Boolean
            Return Me.IsNull(Me.tableOrdenCompraDetalle.ORDCD_PrecioUnitarioColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetORDCD_PrecioUnitarioNull()
            Me(Me.tableOrdenCompraDetalle.ORDCD_PrecioUnitarioColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsORDCD_SubImporteCompraNull() As Boolean
            Return Me.IsNull(Me.tableOrdenCompraDetalle.ORDCD_SubImporteCompraColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetORDCD_SubImporteCompraNull()
            Me(Me.tableOrdenCompraDetalle.ORDCD_SubImporteCompraColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class OrdenCompraRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As OrdenCompraRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As OrdenCompraRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As OrdenCompraRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class OrdenCompraDetalleRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As OrdenCompraDetalleRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As OrdenCompraDetalleRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As OrdenCompraDetalleRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
